application: jonnytv
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.(gif|png|jpg|ico|swf|xml))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|swf|xml))

- url: /js
  static_dir: js

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest




